#%RAML 0.8
title: Telosys REST
version: v1
baseUri: http://www.telosys.org
protocols: [ HTTP ]
/bundles: 
  get: 
    responses: 
      200: 
        body: 
          application/json: 
/status: 
  get: 
    responses: 
      200: 
        body: 
          text/plain: 
/users/{userId}/projects: 
  get: 
    responses: 
      200: 
        body: 
          application/json: 
  /{projectId}: 
    get: 
      responses: 
        200: 
          body: 
            application/json: 
    put: 
      body: 
        application/json: 
      responses: 
        200: 
          body: 
            application/json: 
    /bundles: 
      get: 
        responses: 
          200: 
            body: 
              application/json: 
      /{bundleName}: 
        put: 
          responses: 
            200: 
              body: 
                application/json: 
        delete: 
          responses: 
            200: 
              body: 
                application/json: 
    /configuration: 
      get: 
        responses: 
          200: 
            body: 
              application/json: 
      put: 
        body: 
          application/json: 
        responses: 
          200: 
            body: 
              application/json: 
    /files/{fileId}: 
      get: 
        responses: 
          200: 
            body: 
              application/json: 
      put: 
        body: 
          application/json: 
        responses: 
          200: 
            body: 
              application/json: 
      delete: 
        responses: 
          200: 
    /folders/{folderId}: 
      put: 
        body: 
          application/json: 
        responses: 
          200: 
            body: 
              application/json: 
      delete: 
        responses: 
          200: 
    /model/{modelName}/bundle/{bundleName}/action/generate: 
      get: 
        responses: 
          200: 
            body: 
              application/json: 
    /workspace: 
      get: 
        description: Get root folder with all sub folders and all files of the project of the authenticated user
        responses: 
          200: 
            description: Root folder
            body: 
              application/json: 
    /zip: 
      get: 
        responses: 
          200: 
            body: 
              application/zip: 
